DROP TABLE IF EXIST users CASCADE;
DROP TABLE IF EXIST maps CASCADE;
DROP TABLE IF EXIST pins CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  descriptions TEXT NOT NULL,
  is_favourite BOOLEAN NOT NULL DEFAULT FALSE
);


CREATE TABLE pins (
  id SERIAL PRIMARY KEY NOT NULL,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  comment TEXT,
  latitude INTEGER NOT NULL,
  longitude INTEGER NOT NULL
);
